### ISSUE TITLE
Cannot find module './formatters'

### ISSUE THREAD

**Issue by justinkchen** [ConsenSys/abi-decoder#26]
Not sure if my tests are failing for some other reason, but I'm getting these errors in my tests:

Any ideas why it can't find a relative loaded module in a nested module?
```
Error: Cannot find module './formatters'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/justinkchen/workspace/set-protocol-contracts/node_modules/web3/lib/solidity/coder.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/justinkchen/workspace/set-protocol-contracts/node_modules/abi-decoder/index.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/justinkchen/workspace/set-protocol-contracts/test/core/setTokenFactory.spec.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at /Users/justinkchen/workspace/set-protocol-contracts/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/justinkchen/workspace/set-protocol-contracts/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/justinkchen/workspace/set-protocol-contracts/node_modules/mocha/lib/mocha.js:536:10)
    at /Users/justinkchen/workspace/set-protocol-contracts/node_modules/truffle/build/webpack:/~/truffle-core/lib/test.js:125:1```

**Comment by justinkchen** [comment]
Never mind it seems like my tsconfig was messed up when setting paths to resolve modules from. removing the custom paths fixed it
