### ISSUE TITLE
exception when decoding receipt logs of some transaction

### ISSUE THREAD

**Issue by kelvinkuo** [ConsenSys/abi-decoder#27]
transaction:0x7834632fb74e671317e87551c5969dcf117efaf00c1f16c4e5d66419715e3b37

when decoding the transaction above, got the exception info:
`Error caught in uncaughtException event: TypeError: Cannot read property 'slice' of undefined                                                                                                                                 
    at /data/ethereum/wallet_server/node_modules/abi-decoder/index.js:112:40
    at Array.map (<anonymous>)
    at Object._decodeLogs [as decodeLogs] (/data/ethereum/wallet_server/node_modules/abi-decoder/index.js:111:15)
    at Object.receiveTransactionReceipt [as callback] (/data/ethereum/wallet_server/ether_scan/ether-scan-test.js:218:36)
    at /data/ethereum/wallet_server/node_modules/web3/lib/web3/batch.js:59:33
    at Array.forEach (<anonymous>)
    at /data/ethereum/wallet_server/node_modules/web3/lib/web3/batch.js:52:12
    at /data/ethereum/wallet_server/node_modules/web3/lib/web3/requestmanager.js:116:9
`

**Comment by kolya182** [comment]
And this is the fix https://github.com/ConsenSys/abi-decoder/pull/11

**Comment by kolya182** [comment]
@denisgranha I think this this can be closed
