### ISSUE TITLE
Cannot decode tx data

### ISSUE THREAD

**Issue by kilicbaran** [ConsenSys/abi-decoder#56]
This is somewhat an edge case but the ERC20 token transfer for this [transaction](https://etherscan.io/tx/0xd4b9846901eaf92b29678ce7003b46c876cf19153022d20229d4bd2ca3b9897d) cannot be decoded. I am not sure whether I should open an issue here or @ethersproject/abi.

### Sample Code
```
const abiDecoder = require('abi-decoder');
const testABI = [{
    "constant": false,
    "inputs": [
        {
            "name": "_to",
            "type": "address"
        },
        {
            "name": "_value",
            "type": "uint256"
        }
    ],
    "name": "transfer",
    "outputs": [
        {
            "name": "",
            "type": "bool"
        }
    ],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
}];
abiDecoder.addABI(testABI);
const testData = "0xa9059cbb0000000000000000000000043f47038d2b20566700a38cd718a537103f7696c9000000000000000000000000000000000000000000000000000000000903c63c";
const decodedData = abiDecoder.decodeMethod(testData);
console.log(decodedData);
```
### Exception
```
/home/ubuntu/node_modules/@ethersproject/abi/lib/coders/array.js:139
                get: function () { throw value; }
                                   ^

_to: value out of range (argument="value", value=20, code=INVALID_ARGUMENT, version=bytes/5.0.1)
    at Logger.makeError (/home/ubuntu/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/home/ubuntu/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at Logger.throwArgumentError (/home/ubuntu/node_modules/@ethersproject/logger/lib/index.js:191:21)
    at Object.hexZeroPad (/home/ubuntu/node_modules/@ethersproject/bytes/lib/index.js:263:16)
    at AddressCoder.decode (/home/ubuntu/node_modules/@ethersproject/abi/lib/coders/address.js:34:45)
    at /home/ubuntu/node_modules/@ethersproject/abi/lib/coders/array.js:93:31
    at Array.forEach (<anonymous>)
    at Object.unpack (/home/ubuntu/node_modules/@ethersproject/abi/lib/coders/array.js:71:12)
    at TupleCoder.decode (/home/ubuntu/node_modules/@ethersproject/abi/lib/coders/tuple.js:39:49)
    at AbiCoder.decode (/home/ubuntu/node_modules/@ethersproject/abi/lib/abi-coder.js:93:22) {
  reason: 'value out of range',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: 20,
  baseType: 'address',
  name: '_to',
  type: 'address'
}
```

I think that there is a typo in the input data for the address parameter and this causes a problem. There is a 4 instead of 0 (I added spaces before and after to make it more readable.)

Function signiture: 0xa9059cbb
Address: 00000000000000000000000 **4** 3f47038d2b20566700a38cd718a537103f7696c9
Value: 000000000000000000000000000000000000000000000000000000000903c63c

**Comment by Alex314Ru** [comment]
I'm facing the same issue with [this transaction](https://etherscan.io/tx/0xcb3f4da7f95e57f9aa393ce5c0506e76f6c5e37cd5ab76c782ade298922fd8b0) at this moment.

**Comment by aminlatifi** [comment]
I have the same problem! 
Actually w had developed our decoder and were not using abi-decoder. Recently our code wasn't working and I tried abi-decoder as an alternative solution to see what happens! The same problem happens again.

Finally I fill all data with zero except the part I need the its value, it meets my requirement.
```
  const [log] = logs;
  const { data } = log;
  // Just keep homeTx
  log.data = `0x${'0'.repeat(128)}${data.substring(130, 130 + 64)}${'0'.repeat(
    data.length - 2 - 128 - 64,
  )};
```

**Comment by dapplion** [comment]
The transaction linked above is not constructed correctly (has a 0x04 byte prefixed to the address) but that shouldn't make the decode crash. Actually the code that is crashing is `@ethersproject/abi` so you may want to open an issue there saying that `@ethersproject/abi` should not assume that `address` parameters are prefixed by zeros

**Comment by ricmoo** [comment]
I've added support in ethers [5.0.12](https://github.com/ethers-io/ethers.js/releases/tag/v5.0.12) for supporting legacy Solidity 0.4 external event data.

For more details, please see https://github.com/ethers-io/ethers.js/issues/891.
